### ISSUE TITLE
Deprecations for version 2.0

### ISSUE THREAD

**Issue by angrykoala** [neo4j/cypher-builder#98]
This Issue lists deprecations in the current version of Cypher Builder to be removed in the next major release
- [x] `Cypher.pointDistance` in favor of `Cypher.point.distance` #96 
- [x] `Cypher.utils.compileCypher` in favor of `env. compile` #127 
- [x] `Cypher.RawCypher` in favor of `Cypher.Raw` #185 
- [x] Use `.with` to add columns into existing with #198
- [x] `Merge.onCreate` in favor of `Merge.onCreateSet` #245  
- [x] `Call.innerWith` in favor of `Call.importWith` #283 
- [x] `PatternComprehension` second parameter in favor of `.map()` #289
- [x] `Cypher.cdc` in favor of `Cypher.db.cdc` #315 
- [x] Labels and Types in  `Cypher.Node` and `Cypher.Relationship` #310
- [x] Pattern constructor with Node and Relationship in favor of using an config object #310
- [x] Node as parameter for Match Create and Merge #310 
- [x] `rTrim` and `lTrim` #378
- [x] Move `concat` to `utils.concat` - #374 
- [x] `Cypher.RawCypherCallback` in favor of `Cypher.Environment` #451 
- [ ] `.build()` parameters #454
  - [ ] `EnvPrefix`

> Note: this does not list Cypher language deprecations

Possible breaking changes to discuss:

- [x] #439
- [x] #229
- [x] #441
- [x] node 16 vs node 18
- [x] #406
